/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#10b981',
        'inverse-on-surface': '#f8fafc',
        'surface-container-high': '#f1f5f9',
        'on-error-container': '#7f1d1d',
        'background': '#F8FAFC',
        'on-primary-fixed': '#064e3b',
        'surface-container-highest': '#e2e8f0',
        'inverse-primary': '#34d399',
        'surface': '#ffffff',
        'on-primary': '#ffffff',
        'error': '#ef4444',
        'primary-container': '#d1fae5',
        'tertiary': '#f59e0b',
        'on-secondary-fixed-variant': '#164e63',
        'secondary-fixed-dim': '#22d3ee',
        'on-background': '#1e293b',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface-container': '#ffffff',
        'primary': '#10b981',
        'surface-container-low': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#fee2e2',
        'on-surface-variant': '#64748b',
        'tertiary-fixed': '#fef3c7',
        'on-secondary': '#ffffff',
        'surface-bright': '#ffffff',
        'on-secondary-container': '#164e63',
        'on-tertiary-fixed-variant': '#78350f',
        'secondary': '#06b6d4',
        'primary-fixed': '#6ee7b7',
        'tertiary-container': '#fef3c7',
        'on-primary-fixed-variant': '#065f46',
        'surface-tint': '#10b981',
        'inverse-surface': '#1e293b',
        'on-primary-container': '#064e3b',
        'tertiary-fixed-dim': '#fbbf24',
        'on-tertiary-fixed': '#451a03',
        'outline-variant': '#e2e8f0',
        'secondary-fixed': '#a5f3fc',
        'on-tertiary-container': '#78350f',
        'secondary-container': '#ecfeff',
        'surface-variant': '#f1f5f9',
        'surface-dim': '#f8fafc',
        'outline': '#cbd5e1',
        'on-surface': '#0f172a',
        'on-secondary-fixed': '#083344'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'md': '16px',
        'gutter': '20px',
        'sm': '8px',
        'container-max': '1440px',
        'xs': '4px',
        'lg': '24px',
        'base': '4px',
        'xl': '40px'
      },
      fontFamily: {
        'headline-md': ['IBM Plex Sans', 'sans-serif'],
        'body-md': ['IBM Plex Sans', 'sans-serif'],
        'headline-sm': ['IBM Plex Sans', 'sans-serif'],
        'code-sm': ['IBM Plex Sans', 'monospace'],
        'body-lg': ['IBM Plex Sans', 'sans-serif'],
        'display-lg': ['IBM Plex Sans', 'sans-serif'],
        'label-md': ['Stack Sans Text', 'sans-serif'],
        'sans': ['IBM Plex Sans', 'Stack Sans Text', 'sans-serif'],
        'serif': ['Lora', 'Noto Serif', 'Roboto Slab', 'serif'],
        'ibm-plex': ['IBM Plex Sans', 'sans-serif'],
        'lora': ['Lora', 'serif'],
        'noto-serif': ['Noto Serif', 'serif'],
        'roboto-slab': ['Roboto Slab', 'serif'],
        'stack-sans': ['Stack Sans Text', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'section-heading': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'card-title': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-text': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'table-header': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'table-data': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'sidebar-menu': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'button-text': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }]
      }
    },
  },
  plugins: [],
}
